name = "QSymBase"
uuid = "a8697a1a-c835-4068-9491-e8abc49d0056"
authors = ["Stefan Krastanov <stefan@krastanov.org> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuantumCore = "5717a53b-5d69-4fa3-b976-0bf2f97ca1e5"
SnoopPrecompile = "66db9d55-30c0-4569-8b51-7e840670fc0c"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"

[compat]
QuantumCore = "0.1.0"
SnoopPrecompile = "1"
SymbolicUtils = "0.19.11"
Symbolics = "4.10.4"
TermInterface = "0.2.3, 0.3"
julia = "1.8"
