name = "QuantumSymbolics"
uuid = "efa7fd63-0460-4890-beb7-be1bbdfbaeae"
authors = ["QuantumSymbolics.jl contributors"]
version = "0.2.0"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
QuantumInterface = "5717a53b-5d69-4fa3-b976-0bf2f97ca1e5"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"

[weakdeps]
QuantumClifford = "0525e862-1e90-11e9-3e4d-1b39d7109de1"
QuantumOpticsBase = "4f57444f-1401-5e15-980d-4471b28d5678"

[extensions]
MixedCliffordOpticsExt = ["QuantumClifford", "QuantumOpticsBase"]
QuantumCliffordExt = "QuantumClifford"
QuantumOpticsExt = "QuantumOpticsBase"

[compat]
Graphs = "1.7.3"
Latexify = "0.15"
PrecompileTools = "1"
QuantumClifford = "0.8"
QuantumInterface = "0.1.0"
QuantumOpticsBase = "0.3.8"
SymbolicUtils = "1"
Symbolics = "5"
TermInterface = "0.3"
julia = "1.9"
